//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIAA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CORE_LOGIN
    {
        public int ID { get; set; }
        public string USUARIO { get; set; }
        public string CONTRASENA { get; set; }
        public Nullable<int> ID_CORE_USUARIO { get; set; }
    
        public virtual CORE_USUARIOS CORE_USUARIOS { get; set; }
    }
}
