//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIAA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class atencionCiudadanaEntities : DbContext
    {
        public atencionCiudadanaEntities()
            : base("name=atencionCiudadanaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CORE_LOGIN> CORE_LOGIN { get; set; }
        public virtual DbSet<CORE_ROLES> CORE_ROLES { get; set; }
        public virtual DbSet<CORE_USUARIOS> CORE_USUARIOS { get; set; }
    }
}
